authenticator/urls.py
from django.urls import path

from . import views

app_name = 'auth'
urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('check/', views.check, name='check'),
    path('logout/', views.log_out)
]

game/urls.py
from django.urls import path

from . import views

app_name = "game"

urlpatterns = [
    path('', views.index, name="index"),
    path('place/<slug:name>/', views.place, name="place"),
    path('decision/', views.decision, name="decision"),
    path('result/', views.result, name="result"),

    path('items/<slug:name>/', views.items),
    path('items/send/<slug:name>/', views.items_send),
    path('questions/person/<int:personid>/', views.get_questions),
    path('questions/<int:questionid>/', views.ask_question),
    path('questions/confirm/<int:personid>/', views.confirm_beginning),
    path('events/<slug:page>', views.check_events),
    path('submit/<slug:submit_id>/<slug:value>', views.inspector_submit),
    path('chat/<slug:name>', views.approve_chat)
]

sarah_game/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls'), name='game'),
    path('accounts/', include('authenticator.urls'), name='auth')
]

authenticator/models.py
from django.db import models

# Create your models here.

authenticator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from game.models import *

from django.utils import timezone


def log_in(request):
    template = loader.get_template('authenticator/loginnew.html')
    context = {
        'user': request.user,
        'next': request.GET.get('next'),
    }
    return HttpResponse(template.render(context, request))

def log_out(request):
    logout(request)
    response = HttpResponse("You have been logged out successfully")
    response.delete_cookie('access_token')
    return response

def check(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)

    if user is not None:
        login(request, user)
        if not hasattr(user, "player"):
            create_new_player(user)

        return redirect('game:index')
    else:
        return redirect('auth:login')
# Create your views here.

def create_new_player(user):
    p = Player(user=user)
    p.save()

    knife = Item(data=ItemMeta.objects.get(id=1), player=p)
    knife.save()
    phone = Item(data=ItemMeta.objects.get(id=2), player=p)
    phone.save()
    high_heels = Item(data=ItemMeta.objects.get(id=3), player=p)
    high_heels.save()
    beginning = Event.objects.get(desc="Beginning")
    ce = CausedEvent(event=beginning, player=p, time=timezone.now())
    ce.save()

authenticator/templates/authenticator/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
  </head>
  <body>
    <br><br><br>
    {% if user.is_authenticated %}
      You are already looged in.
    {% else %}
    <form action="{%url 'auth:check' %}" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td>Username:</td>
          <td><input type="text" name="username" value=""></td>
        </tr>
        <tr>
          <td>Password:</td>
          <td><input type="password" name="password" value=""></td>
        </tr>
      </table>
      {% if next %}
    <input type="hidden" name="next" value="{{ next }}">
      {% endif %}
    <input type="submit" value="Login">
  </form>
    {% endif %}
  <br>
  Diese Webseite verwendet Cookies und Javascript.<br>
  Bitte beides ggf. zu enablen. <br>
  Volle Funktionalität ist leider zur Zeit nur im Firefox-Browser gegeben. <br>
  

  </body>
</html>

authenticator/templates/authenticator/loginnew.html
{% load static %}
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Login</title>
		<link rel="stylesheet" href="{% static 'game/main.css'%}">
		<meta name="viewport" content="user-scalable=yes, width=1240">
		<style media="screen">
			body {
				background-color: black;
			}
			table {
				position: absolute;
				left: 500px;
				top: 300px;
				color: white;
			}
			#login {
				position: absolute;
				left: 610px;
				top: 400px;
			}
			#notiz {
				position: absolute;
				left: 400px;
				top: 500px;
				color: white;
				text-align: center;
			}
			</style>
	</head>
  <body class="stop-scrolling">

	<div id="main_container">

		<div id="wall_top" class="wall"></div>
		<div id="wall_left" class="wall"></div>
		<div id="wall_right" class="wall"></div>
		<div id="wall_bottom" class="wall"></div>

		{% if user.is_authenticated %}
      You are already looged in.
    {% else %}
    <form action="{%url 'auth:check' %}" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td>Username:</td>
          <td><input type="text" name="username" value=""></td>
        </tr>
        <tr>
          <td>Password:</td>
          <td><input type="password" name="password" value=""></td>
        </tr>
      </table>
      {% if next %}
    <input type="hidden" name="next" value="{{ next }}">
      {% endif %}
    <input type="submit" value="Login" id="login">
  </form>
    {% endif %}

	<div id="notiz">
		Diese Webseite verwendet Cookies und Javascript.<br>
		Bitte beides ggf. zu enablen. <br>
		Volle Funktionalität ist leider zur Zeit nur im Firefox-Browser gegeben. <br>
	</div>
</div>

</body>
</html>