game/urls.py
from django.urls import path

from . import views

app_name = "game"

urlpatterns = [
    path('', views.index, name="index"),
    path('place/<slug:name>/', views.place, name="place"),
    path('decision/', views.decision, name="decision"),
    path('result/', views.result, name="result"),

    path('items/<slug:name>/', views.items),
    path('items/send/<slug:name>/', views.items_send),
    path('questions/person/<int:personid>/', views.get_questions),
    path('questions/<int:questionid>/', views.ask_question),
    path('questions/confirm/<int:personid>/', views.confirm_beginning),
    path('events/<slug:page>', views.check_events),
    path('submit/<slug:submit_id>/<slug:value>', views.inspector_submit),
    path('chat/<slug:name>', views.approve_chat)
]

sarah_game/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls'), name='game'),
    path('accounts/', include('authenticator.urls'), name='auth')
]

game/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from datetime import timedelta



class Place(models.Model):
    name = models.CharField(max_length=100)
    display_name = models.CharField(max_length=100, default="")
    html_id = models.CharField(max_length=100)
    background_img = models.CharField(max_length=100, null=True, blank=True)
    visitable_by_default = models.BooleanField(default=False)

    def __str__(self):
        return self.display_name


class Person(models.Model):
    name = models.CharField(max_length=100)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    is_suspect = models.BooleanField(default=True)

    def __str__(self):
        return f"({self.id}){self.name}"

    def available_questions(self, player):
        anfangssatz = self.question_set.get(is_beginning=True)
        asked_questions = player.asked_questions()

        if not anfangssatz in asked_questions:
            return [anfangssatz]

        if self.name == "Mister Stripper":
            e = Event.objects.get(desc="Stripper_Unlocked")
            if not e in player.caused_events():
                insp = InspectorText.objects.get(title="Name?")
                dict = {'break':True, 'return':{'type':'INSPECTOR', 'insp':{
                    'title':insp.title,
                    'text':insp.text}}}
                if insp.HTMLInput != None:
                    if insp.HTMLInput == "button":
                        dict['return']['insp']['button'] = True
                    elif insp.HTMLInput == "input":
                        dict['return']['insp']['input'] = True
                        dict['return']['insp']['submitid'] = insp.submit_id
                    else:
                        dict['return']['insp']['button'] = True
                        dict['return']['insp']['input'] = True
                        dict['return']['insp']['submitid'] = insp.submit_id
                    if insp.ButtonValue != None:
                        dict['return']['insp']['value'] = insp.ButtonValue
                ce = Event.objects.get(desc="Stripper_Question")
                finish_event(ce, player)
                return dict
            elif not player.causedevent_set.get(event=e).finished:
                return [self.question_set.get(text="Anfangssatz 2")]

        questions = self.question_set.all()
        unasked_questions = []

        for question in questions:
            if not question in asked_questions:
                if question.gets_unlocked:
                    try:
                        if player.causedevent_set.get(event=question.on_event):
                            unasked_questions.append(question)
                    except:
                        print("not found")
                elif not question.is_child():
                    unasked_questions.append(question)
                elif question.parentquestion in asked_questions: #if child
                    unasked_questions.append(question)
        return unasked_questions



    def questions_permitted(self, player):
        asked_questions = player.askedquestion_set.all()
        counter = 0

        for question in asked_questions:
            if question.question.person == self and question.was_asked_recently():
                counter += 1

        if self.name == "Mister Stripper":
            if counter > 6:
                return False
            else:
                return True
        elif counter > 4:
            return False
        else:
            return True

class Event(models.Model):
    desc = models.CharField(max_length=200)

    def __str__(self):
        return self.desc

    def auto_finished(self):
        if self.desc == "Stripper_Unlocked":
            return False
        return False if hasattr(self, "causes_inspector") else True

class CausedEvent(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    time = models.DateTimeField(null=True, blank=True)
    finished = models.BooleanField(default=False)
    #finished soll automatisch True sein, wenn das Event nur Fragen auslöst und sonst nix.

    def __str__(self):
        return f"({self.player.user.username})-{self.event.desc}"

class Question(models.Model):
    text = models.CharField(max_length=100, blank=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    gets_unlocked = models.BooleanField(default=False)
    is_beginning = models.BooleanField(default=False)
    video_title = models.CharField(max_length=100, blank=True)
    parentquestion = models.ForeignKey("self", related_name="child_questions", on_delete=models.CASCADE, blank=True, null=True)
    causes_event = models.OneToOneField(Event, related_name="caused_by_question", on_delete=models.CASCADE, blank=True, null=True)
    on_event = models.ForeignKey(Event, related_name="causes_questions", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"({self.id})-[{self.person.name}]-{self.text[:30]}"

    def is_child(self):
        if self.parentquestion != None:
            return True
        else:
            return False

    def has_children(self):
        if len(self.child_questions.all()) > 0:
            return True
        else:
            return False

    def was_asked(self, player):
        if self in player.asked_questions():
            return True
        else:
            return False

class AskedQuestion(models.Model):
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    time = models.DateTimeField()

    def __str__(self):
        return f"{self.player.user.username}_[{self.question.person.name}]_{self.question.text[:30]}"
    def was_asked_recently(self):
        return self.time >= timezone.now() - timedelta(minutes=10)

class QuestionInterrupt(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    stop_time = models.FloatField()
    resume_time = models.FloatField()
    inspector_text = models.OneToOneField("InspectorText", on_delete=models.CASCADE)
    unique_id = models.CharField(max_length=30, null=True, blank=True)

class InspectorText(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=600)
    causes_event = models.OneToOneField(Event, related_name="caused_by_inspector", on_delete=models.CASCADE, blank=True, null=True)
    on_event = models.OneToOneField(Event, related_name="causes_inspector", on_delete=models.CASCADE, blank=True, null=True)
    parenttext = models.OneToOneField("self", related_name="child", on_delete=models.CASCADE, blank=True, null=True)
    page = models.CharField(max_length=100, blank=True, null=True)
    finishes_event = models.ForeignKey(Event, related_name="finished_by_inspector", on_delete=models.CASCADE, blank=True, null=True)
    HTMLInput = models.CharField(max_length=20, blank=True, null=True)
    ButtonValue = models.CharField(max_length=20, blank=True, null=True)
    submit_id = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.title + (" nach: " + self.parenttext.title if self.has_parent() else "")

    def has_parent(self):
        return self.parenttext != None

    def has_child(self):
        return hasattr(self, "child")

class ItemMeta(models.Model):
    name = models.CharField(max_length=100)
    desc_text = models.CharField(max_length=500)
    exam_text = models.CharField(max_length=500)
    img_name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Item(models.Model):
    is_visible = models.BooleanField(default=True)
    is_examined = models.BooleanField(default=False)
    sent_away_time = models.DateTimeField(null=True, blank=True)
    data = models.ForeignKey(
        ItemMeta,
        on_delete = models.CASCADE
    )
    player = models.ForeignKey(
        "Player",
        on_delete = models.CASCADE
    )
    def __str__(self):
        return self.data.name + " " + self.player.user.username

class IntermediateStand(models.Model):
    submit_id = models.CharField(max_length=25)
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    value = models.CharField(max_length=25)
    time = models.DateTimeField()

class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    park_visitable = models.BooleanField(default=False)
    old_but_gold_visitable = models.BooleanField(default=False)
    twoinone_visitable = models.BooleanField(default=False)
    cafe_visitable = models.BooleanField(default=False)

    met_felix = models.BooleanField(default=False)
    met_julian = models.BooleanField(default=False)
    met_sophia = models.BooleanField(default=False)
    met_honey = models.BooleanField(default=False)
    met_stripper = models.BooleanField(default=False)

    final_score = models.IntegerField(null=True, blank=True)

    #caused_events = models.ForeignKey(CausedEvent, on_delete=models.CASCADE, blank=True, null=True)
    #asked_questions = models.CharField(max_length=500, null=True)
    def __str__(self):
        return self.user.username

    def asked_questions(self):
        return [q.question for q in self.askedquestion_set.all()]

    def caused_events(self):
        return [e.event for e in self.causedevent_set.all()]

    def has_finished(self):
        return True if self.final_score is not None else False

def finish_event(event, player):
    e = player.causedevent_set.get(event=event)
    e.finished = True
    e.save()

game/templates/game/decision.html
{% load static %}
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge">
		<title>Decision</title>
	  <link rel="stylesheet" href=" {% static 'game/decision.css' %}">
  </head>
	<body>
	<div id="main_container" style="margin: auto; position: relative; width: 1240px; height: 800px; overflow: hidden; -webkit-transform-style: flat;" hyp_dn="Decision">
		<div class="wall" id="wall_left"></div>
		<div class="wall" id="wall_right"></div>
		<div class="wall" id="wall_top"></div>
		<div class="wall" id="wall_bottom"></div>

		<div id="note"></div>
		<div id="note_text">
			Zurück
		</div>

		<div class="dimmer" id="felix_dimmer"></div>
		<div class="dimmer" id="sophia_dimmer"></div>
		<div class="dimmer" id="julian_dimmer"></div>
		<div class="dimmer" id="stripper_dimmer"></div>
		<div class="dimmer" id="honey_dimmer"></div>


		<div class="img" id="felix_img"></div>
		<div class="img" id="sophia_img"></div>
		<div class="img" id="julian_img"></div>
		<div class="img" id="stripper_img"></div>
		<div class="img" id="honey_img"></div>



	<div class="bar_container" id="bar_container">
		<div class="bar"></div>
		<div class="bar" style="transform: translateX(29px);"></div>
		<div class="bar" style="transform: translateX(58px);"></div>
		<div class="bar" style="transform: translateX(85px);"></div>
		<div class="bar" style="transform: translateX(114px);"></div>
		<div class="bar" style="transform: translateX(143px);"></div>
		<div class="bar" style="transform: translateX(172px);"></div>
		<div class="bar" style="transform: translateX(201px);"></div>
	</div>

<div  id="button_container" style="pointer-events: auto; position: absolute; overflow: visible; z-index: 36; width: 1143px; height: 59px; transform-origin: 50% 50%; transform: translateX(55px) translateY(678px) rotateY(0deg);">
	<div class="continue_button" id="felix_button"><br></div>
	<div class="continue_button" id="sophia_button"><br></div>
	<div class="continue_button" id="julian_button"><br></div>
	<div class="continue_button" id="stripper_button"><br></div>
	<div class="continue_button" id="honey_button"><br></div>
	</div>
	{% include 'game/insp_popup.html'%}

</div>



<a href="/" hidden="true" id="link"></a>

<form id="submit_form" action="{% url 'game:result' %}" method="post">
	{% csrf_token %}
</form>

</body>
<script type="text/javascript" src="{% static 'game/decision.js' %}"></script>

</html>

game/templates/game/insp_popup.html
{% load static %}
<link rel="stylesheet" href="{% static 'game/inspektor.css' %}">
<div id="insp_popup">
  <div id="insp_popup_background" style=""></div>
    <div id="insp_title" style="">
      TITEL
    </div>
    <div id="insp_text" style="">
      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    </div>
    <div id="insp_img" style=""></div>
    <input type="text" id="insp_text_input" name="" value="">
    <input type="button" id="insp_button_input" name="" value="">
    <div id="insp_close" class="popup_close"></div>
</div>

game/templates/game/item_popup.html
<div id="item_popup">
    <div id="popup_background"></div>
    <div id="popup_knife" class="popup_image"></div>
    <div id="popup_high_heels" class="popup_image"></div>
    <div id="popup_phone" class="popup_image"></div>
    <div id="popup_title">
      TITEL
    </div>
    <div id="popup_text">
      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    </div>
    <input type="button" id="popup_button" name="" value="">
    {% if phone.is_examined %}
    <div id="phone_container">
      <iframe id="overview_iframe" src="/static/game/images/chats_overview.jpg" scrolling="no" seamless></iframe>
      <div id="chats_container">
        <img id="chats_img" src="/static/game/images/felix_chat.png" width="100%"></img>
      </div>
      <iframe id="overlay_iframe" scrolling="no"></iframe>
      <div id="phone_border"></div>
      <div id="phone_close"></div>
      <div id="chat_chooser" style="width: 100%; height: 100%;">
        <div id="felix_chat" class="chat"></div>
        <div id="julian_chat" class="chat"></div>
        <div id="stripper_chat" class="chat"></div>
        <div id="sophia_chat" class="chat"></div>
      </div>

      <div id="back_chat"></div>

      </div>
    {% endif %}
    <div id="item_close" class="popup_close"></div>
</div>

game/templates/game/main.html
{% load static %}
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>startpage</title>
		<link rel="stylesheet" href="{% static 'game/main.css'%}">
		<meta name="viewport" content="user-scalable=yes, width=1240">
	</head>
  <body class="stop-scrolling">

	<div id="main_container">
		<div id="map_container">
			<div id="map" class="img">
				<div id="bank"></div>
				{% if player.cafe_visitable %}
				<div id="cafe"></div>
				{% endif %}
				{% if player.old_but_gold_visitable %}
				<div id="old_but_gold"></div>
				{% endif %}

				{% if player.park_visitable %}
				<div id="park"></div>
				{% endif %}

				{% if player.twoinone_visitable %}
				<div id="twoinone"></div>
				{% endif %}
			</div>
		</div>
		
		{% include 'game/item_popup.html' %}
		{% include 'game/insp_popup.html' %}

		<div id="note_text">Karte</div>
    <div id="metal" class="img"></div>
		<div id="note" class="img"></div>
		<div id="wood" class="img"></div>

		{% if player.item_set.all.0.is_visible %}
			<div id="knife" class="img"></div>
		{% endif %}

		{% if player.item_set.all.1.is_visible %}
	 		<div id="high_heels" class="img"></div>
		{% endif %}

		{% if player.item_set.all.2.is_visible %}
			<div id="phone" class="img"></div>
		{% endif %}


		{% if not player.has_finished %}
	 		<div id="bars" class="img"></div>
		{% else %}
			<div id="bars" style="display:none;"></div>
		{% endif %}

		<div id="wall_top" class="wall"></div>
		<div id="wall_left" class="wall"></div>
		<div id="wall_right" class="wall"></div>
		<div id="wall_bottom" class="wall"></div>

		{% include 'game/people_list.html'%}

</div>

{% for plc in places %}
<form action="{% url 'game:place' plc.html_id %}">
	<input id="go_to_{{ plc.html_id }}" type="submit" hidden="true" name="">
</form>
{% endfor %}


{% if player.met_felix and player.met_sophia and player.met_julian and player.met_stripper and player.met_honey %}
	<form action="{% url 'game:decision' %}" method="get">
		<input type="submit" hidden="true" id="decide_submit">
	</form>
{% endif %}
</body>
<script src="{% static 'game/main.js'%}"></script>
</html>

game/templates/game/people_list.html
{% if player.met_felix %}
  <div class="img person" id="felix" onclick="location.href='/place/cafe';"></div>
{% else %}
  <div class="img silhouette" style="transform: translateX(1027px) translateY(-16px);"></div>
{% endif %}

{% if player.met_julian %}
  <div class="img person" id="julian" onclick="location.href='/place/park';"></div>
{% else %}
  <div class="img silhouette" style="transform: translateX(1027px) translateY(125px);"></div>
{% endif %}

{% if player.met_sophia %}
  <div class="img person" id="sophia" onclick="location.href='/place/old_but_gold';"></div>
{% else %}
  <div class="img silhouette" style="transform: translateX(1027px) translateY(261px);"></div>
{% endif %}

{% if player.met_stripper %}
  <div class="img person" id="stripper" onclick="location.href='/place/twoinone';"></div>
{% else %}
  <div class="img silhouette" style="transform: translateX(1027px) translateY(400px);"></div>
{% endif %}

{% if player.met_honey %}
  <div class="img person" id="honey" onclick="location.href='/place/twoinone';"></div>
{% else %}
  <div class="img silhouette" style="transform: translateX(1027px) translateY(545px);"></div>
{% endif %}

game/templates/game/place.html
{% load static %}
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Places</title>
		<link rel="stylesheet" href="{% static 'game/place.css' %}">
		<link rel="stylesheet" href="{% static 'game/video.css' %}">
  </head>
  <body>
	<div id="main_container">
        <div class="wall" id="wall_left"></div>
        <div class="wall" id="wall_top"></div>
        <div class="wall" id="wall_bottom"></div>
        <div class="wall" id="wall_right"></div>

				{% include 'game/videopopup.html' %}

				<div id="place_name">
					{{ place.display_name }}
				</div>

				{% if place.person_set.all|length == 2 %}
					{% if setup_finished %}
						{% if place.name == 'twoinone'%}
						{% if met_honey == True %}
							<div id="dimmer_left" class="dimmer" data-personid="{{ place.person_set.all.1.id }}"></div>
						{% else %}
							<div id="dimmer_left" class="dimmer" style="opacity: 1"></div>
						{% endif %}
						<div id="dimmer_right" class="dimmer" data-personid="{{ place.person_set.all.0.id }}"></div>
						{% elif place.name == "old_but_gold" %}
							<div id="dimmer_left" class="dimmer" data-personid="{{ place.person_set.all.0.id }}"></div>
							{% if met_sophia %}
								<div id="dimmer_right" class="dimmer" data-personid="{{ place.person_set.all.1.id }}"></div>
							{% else %}
								<div id="dimmer_right" class="dimmer" style="opacity: 1"></div>
							{% endif %}
						{% else %}
						<div id="dimmer_left" class="dimmer" data-personid="{{ place.person_set.all.0.id }}"></div>
						<div id="dimmer_right" class="dimmer" data-personid="{{ place.person_set.all.1.id }}"></div>
						{% endif %}
					{% endif %}

	        <div class="person_name" id="person1_name">
					{% if place.name == 'twoinone' %}
						{% if met_honey == True %}
          		{{ place.person_set.all.1.name }}
						{% endif %}
					{% else %}
						{{ place.person_set.all.0.name }}
					{% endif %}

	        </div>
	        <div class="person_name" id="person2_name">
					{% if place.name == 'twoinone' %}
          	{{ place.person_set.all.0.name }}
					{% elif place.name == 'old_but_gold' %}
						{% if met_sophia == True %}
							{{ place.person_set.all.1.name }}
						{% endif %}
					{% else %}
						{{ place.person_set.all.1.name }}
					{% endif %}
	        </div>

				{% else %}
					{% if setup_finished %}
					<div id="dimmer_whole" class="dimmer" data-personid="{{ place.person_set.all.0.id }}"></div>
					{% endif %}
					<div class="person_name" id="single_person_name">
						{{ place.person_set.all.0.name }}
					</div>


				{% endif %}


        <div id="note"></div>
        <div id="background" style="background-image: url('/static/game/backgrounds/{{ place.background_img }}');"></div>
        <div id="map"></div>

				{% include 'game/insp_popup.html' %}
  </div>

<form action="{% url 'game:index' %}" method="get">
<input id="back_to_map" type="submit" hidden="true">
</form>



<script type="text/javascript" src="{% static 'game/place.js' %}"></script>

</body>
</html>

game/templates/game/videopopup.html
{% load static %}
	<div id="video-container">
			<div id="background-dimmer"></div>
			<div id="video-frame"></div>
			<div id="video-dimmer"></div>
			<div id="video-parent">
				<div id="video-background">
				<video id="video"></video>
				</div>
			</div>
			<div id="question-container"></div>
	</div>